### ISSUE TITLE
More refactoring on classes

### ISSUE THREAD

**Issue by AhmedAbdelmoneim** [Siddarth-Raghuvanshi/sgRNAble#9]
- Magic numbers
- Use Pathlib for paths, should be injected into dependent classes
- Public vs private functions
- Class and function naming
- Function arguments (some functions accept more arguments than necessary, ex. passing the entire args object)
- Split longer functions into helpers

**Comment by Siddarth-Raghuvanshi** [comment]
refactor casmodel for me
